# This is a basic workflow to help you get started with Actions

name: CI_Cross_Org_PubicWflow_PublicAction

# Controls when the workflow will run
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - uses: new-action-flow-test-org-1/addash-public-action@main
